version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: express_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase?schema=public
      - NODE_ENV=production
      - JWT_SECRET=your_secret_token_here
      - JWT_EXPIRY=24h
      - JWT_REFRESH=your_refresh_token_here
      - JWT_REFRESH_EXPIRY=7d
      - MAIL_HOST=smtp.your_email_provider.com
      - MAIL_PORT=your_email_port_here
      - MAIL_USER=your_email_here
      - MAIL_SECURE=false
      - MAIL_PASS=your_email_password_here
      - CLIENT_DOMAIN=https://your-production-domain.com
      - CLIENT_LOCAL_PORT=5173
      - COMPANY_NAME=YourCompany
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
      - /app/node_modules
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:prod"

volumes:
  postgres_data: